In [25]:
import pickle
import numpy as np
import sklearn as sk

In [2]:
with open('hw3_q1.pkl', 'rb') as f:
    data = pickle.load(f)

In [3]:
print(type(data))

<class 'dict'>


In [4]:
print(data.keys())

dict_keys(['x', 'y'])


In [5]:
print(data['x'].shape)

(50, 3)


In [6]:
print(data['y'].shape)

(50, 1)


In [8]:
X = np.asarray(data['x'])

In [10]:
Y = np.asarray(data['y'])

In [18]:
result1 = np.matmul(np.matmul(np.linalg.inv(np.matmul(np.transpose(X), X)), np.transpose(X)), Y)

In [19]:
result1

array([[ 0.88914862],
       [-0.82601591],
       [ 4.19023612]])

In [20]:
result2 = np.matmul(np.matmul(np.linalg.inv(np.matmul(np.transpose(X), X) + np.eye(3)), np.transpose(X)), Y)

In [21]:
result2

array([[ 0.86455156],
       [-0.82104237],
       [ 4.12186079]])

In [26]:
from sklearn.linear_model import Lasso

In [34]:
sparse_lasso = Lasso(alpha=1, max_iter=1000)

In [35]:
sparse_lasso.fit(X, Y)

Lasso(alpha=1)

In [36]:
sparse_lasso.coef_

array([ 0.        , -0.21282935,  3.36516248])